version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 36000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  traefik:
    image: traefik:v2.3
    container_name: traefik
    depends_on:
      - watchtower
    domainname: ${TRAEFIK_DOMAIN}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_PATH}/traefik/certs:/letsencrypt/
    command:
      - "--providers.docker=true"
      - "--providers.docker.network=discovery"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # configure endpoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # SSL configuration
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.email=${TRAEFIK_MAIL}"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.api-auth.basicauth.users=${TRAEFIK_USER}"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_SUBDOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    networks:
      - default
      - discovery
    dns:
      - ${TRAEFIK_DNS1}
      - ${TRAEFIK_DNS2}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  webirc:
    image: thelounge/thelounge:latest
    container_name: webirc
    volumes:
      - ${CONFIG_PATH}/irc:/var/opt/thelounge 
    networks:
      - discovery
    ports:
      - 113:9001
      - 9000:9000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.irc-http.entrypoints=web"
      - "traefik.http.routers.irc-http.rule=Host(`${IRC_DOMAIN}`)"
      - "traefik.http.routers.irc-http.middlewares=irc-https"
      - "traefik.http.middlewares.irc-https.redirectscheme.scheme=https"
      - "traefik.http.routers.irc.entrypoints=websecure"
      - "traefik.http.routers.irc.rule=Host(`${IRC_DOMAIN}`)"
      - "traefik.http.routers.irc.tls=true"
      - "traefik.http.routers.irc.tls.certresolver=letsencryptresolver"
      - "traefik.docker.network=discovery"
      - "com.centurylinklabs.watchtower.enable=true"
  pihole:
    image: pihole/pihole:nightly
    container_name: pihole
    depends_on:
      - watchtower
    domainname: ${TRAEFIK_DOMAIN}
    restart: unless-stopped
    networks:
      - discovery
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:67:67/udp'
      - '0.0.0.0:8053:80/tcp'
      - "0.0.0.0:8054:443/tcp"
    volumes:
      - ${CONFIG_PATH}/pihole/etc-pihole/:/etc/pihole/
      - ${CONFIG_PATH}/pihole/etc-dnsmasqd/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - ${PIHOLE_DNS1}
      - ${PIHOLE_DNS2}
    environment:
      ServerIP: ${PIHOLE_IP}
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_PASS}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: ${PIHOLE_DOMAIN}
      VIRTUAL_PORT: ${PIHOLE_PORT}
      DNS1: ${PIHOLE_DNS1}
      DNS2: ${PIHOLE_DNS2}
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_DOMAIN}`)"
       - "traefik.http.routers.pihole.entrypoints=web"
       - "traefik.docker.network=discovery"
       - "traefik.http.services.pihole.loadbalancer.server.port=${PIHOLE_PORT}"
       - "com.centurylinklabs.watchtower.enable=true"
  samba:
    image: dperson/samba
    depends_on:
      - watchtower
    environment:
      TZ: ${TIMEZONE}
    networks:
      - shareNetwork
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${SAMBA_HOST_VOLUME}:/mnt:z
    command: '-s "media;/mnt;yes;no;no;${SAMBA_USER}" -u "${SAMBA_USER};${SAMBA_PASS}" -p -w "${SAMBA_WORKGROUP}"'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  shareNetwork:
  discovery:
    external: true